---
theme: "hugo-tranquilpeak-theme"

baseURL: "https://hapana.github.io/"
languageCode: "en-us"
title: "'Articles"

author:
  name: "Harry P"
  bio: "Okayish person"
  job: "DevOops"
  picture: "/avatar.jpeg"

menu:
  main:
    - identifier: "articles"
      name: "Articles"
      title: "Blog"
      url: "/posts/"
      weight: 1
  links:
    - identifier: "github"
      name: "GitHub"
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
      url: "https://github.com/hapana/"
      weight: 1
    - identifier: "linkedin"
      name: "LinkedIn"
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
      url: "https://www.linkedin.com/in/harrypan/"
      weight: 1

params:
  coverImage: "images/cover.jpg"
  sidebarBehavior: 1
  autoThumbnailImage: true
  description: "Stuff I do"
  thumbnailImage: true
