---
theme: "hyde"

baseURL: "https://hapana.github.io/"
languageCode: "en-us"
title: "Harry P"

Menus:
  main:
    - Name: "Github"
      URL: "https://github.com/hapana/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/harrypan/"

params:
  description: "Posts and stuff"
